apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitops-ci-hw
  name: gitops-ci-hw
spec:
  replicas: 5
  selector:
    matchLabels:
      app: gitops-ci-hw
      version: v1.0.0
  template:
    metadata:
      labels:
        app: gitops-ci-hw
        version: v1.0.0
    spec:
      containers:
        - image: gitops-ci-hw
          name: gitops-ci-hw
          ports:
            - name: http
              containerPort: 8050
