apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitops-ci-hw
  name: gitops-ci-hw-v2
spec:
  replicas: 5
  selector:
    matchLabels:
      app: gitops-ci-hw
      version: v2.0.0
  template:
    metadata:
      labels:
        app: gitops-ci-hw
    spec:
      containers:
        - image: gitops-ci-hw
          name: gitops-ci-hw
          ports:
            - name: http
              containerPort: 8050