apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitops-ci-hw
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gitops-ci-hw
                port:
                  number: 80