apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- app-v1.yaml
- service.yaml
- ingress.yaml
images:
- name: gitops_ci_hw
  newName: olesiayav/gitops_ci_hw
  newTag: c231f4bf738535df912638b2f42b820fe250d0a6
- name: hello-gitops
  newName: olesiayav/hello-gitops
  newTag: 89631119458a61d6c14730512ec5fb1c0413f00a
namespace: hello-gitops
