apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- app-v1.yaml
- service.yaml
- ingress.yaml
namespace: gitops-ci-hw
images:
- name: gitops_ci_hw
  newName: olesiayav/gitops_ci_hw
  newTag: c231f4bf738535df912638b2f42b820fe250d0a6
