apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitops_ci_hw
  name: gitops_ci_hw
spec:
  ports:
    - name: http
      port: 8050
      targetPort: http
  selector:
    app: gitops_ci_hw
  type: ClusterIP