name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
#  test:
#    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: ./app
#
#    steps:
#    - name: Checkout code
#      uses: actions/checkout@v3
#
#    - name: Set up Python
#      uses: actions/setup-python@v4
#      with:
#        python-version: '3.11'
#
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install -r requirements.txt
#
#    - name: Run tests
#      run: |
#        pytest
#
#    - name: Set up Docker Buildx
#      id: buildx
#      uses: docker/setup-buildx-action@v2
#
#    - name: Debug Docker tag
#      run: |
#        echo "Tag: ${{ secrets.DOCKER_USERNAME }}/gitops-ci-hw:${{ github.sha }}"
#
#    - name: Cache Docker layers
#      uses: actions/cache@v3
#      with:
#        path: /tmp/.buildx-cache
#        key: ${{ runner.os }}-buildx-${{ github.sha }}
#        restore-keys: |
#          ${{ runner.os }}-buildx-
#
#    - uses: docker/login-action@v2
#      with:
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}
#
#    - name: Build and push
#      uses: docker/build-push-action@v5
#      with:
#        context: ./app
#        file: ./app/Dockerfile
#        builder: ${{ steps.buildx.outputs.name }}
#        push: true
#        tags: ${{ secrets.DOCKER_USERNAME }}/gitops_ci_hw:${{ github.sha }}, ${{ secrets.DOCKER_USERNAME }}/gitops_ci_hw:latest
#        platforms: linux/amd64,linux/arm64
#        cache-from: type=local,src=/tmp/.buildx-cache
#        cache-to: type=local,dest=/tmp/.buildx-cache

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
#    needs: test

    env:
      PROJECT_ID: ${{ secrets.GKE_PROJECT }}
      GKE_CLUSTER: autopilot-cluster-1
      GKE_REGION: us-central1

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "3.6.1"

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2.1.7
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2.1.2

    - name: Install gke-gcloud-auth-plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin --quiet

    - name: Use GKE gcloud auth plugin
      env:
        USE_GKE_GCLOUD_AUTH_PLUGIN: "True"
      run: echo "Using GKE gcloud auth plugin"

    - name: Get the GKE credentials so we can deploy to the cluster
      run: |
        gcloud container clusters get-credentials "$GKE_CLUSTER" --region "$GKE_REGION"

    - name: Set up Kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

#    - name: Apply v1 deployment
#      run: |
#        kubectl apply -f ./k8s/app-v1.yaml
#
#    - name: Apply Service
#      run: |
#        kubectl apply -f ./k8s/service.yaml

    - name: Get the latest deployment version and set the version variable
      id: version
      run: |
        CURRENT_VERSION=$(kubectl get deployments -n gitops-ci-hw -o json | \
          jq -r '.items[] | select(.metadata.name | test("^gitops-ci-hw-")) | .metadata.name' | \
          grep -o '[0-9]*$' | sort -n | tail -n 1)

        if [ -z "$CURRENT_VERSION" ]; then
          CURRENT_VERSION=1
        fi

        NEXT_VERSION=$((CURRENT_VERSION + 1))
        echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_ENV

    - name: Update app-v1.yaml with the new version
      run: |
        # Replace the placeholder ${VERSION} with the new version from NEXT_VERSION
        sed -i "s/gitops-ci-hw-\${VERSION}/gitops-ci-hw-${{ env.NEXT_VERSION }}/" ./k8s/app-v1.yaml

    - name: Display CURRENT_VERSION, NEXT_VERSION, and Files
      run: |
        # Display the CURRENT_VERSION and NEXT_VERSION
        echo "CURRENT_VERSION: $CURRENT_VERSION"
        echo "NEXT_VERSION: $NEXT_VERSION"

        # Display the contents of the kustomization.yaml file
        echo "kustomization.yaml contents:"
        cat ./k8s/kustomization.yaml

        # Display the contents of the app-v1.yaml file
        echo "app-v1.yaml contents:"
        cat ./k8s/app-v1.yaml


    - name: Build and apply Kustomize deployment
      run: |
        kustomize build ./k8s | kubectl apply -f -

    - name: Verify deployment
      run: |
        kubectl get deployments -n gitops-ci-hw

    - name: Apply v2 deployment
      run: |
        kubectl apply -f ./k8s/app-v1.yaml

    - name: Check Success of v2 deployment
      run: |
        kubectl rollout status deploy gitops-ci-hw-v${{ env.NEXT_VERSION }} -w

    - name: Patch service
      run: |
        kubectl patch service gitops-ci-hw -p '{"spec":{"selector":{"version":"${{ env.NEXT_VERSION }}"}}}'

    - name: Delete v1
      run: |
        kubectl delete deploy my-app-v${{ env.CURRENT_VERSION }}




